<?php

/**
 * BaseSystem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $acronym
 * @property string $jiraComponent
 * @property string $dependencies
 * @property string $svnCopyFolder
 * @property string $ftpPath
 * @property string $releaseUrl
 * @property string $testUrl
 * @property enum $sourceFolderCompressionType
 * @property Doctrine_Collection $Baseline
 * 
 * @method string              getName()                        Returns the current record's "name" value
 * @method string              getAcronym()                     Returns the current record's "acronym" value
 * @method string              getJiraComponent()               Returns the current record's "jiraComponent" value
 * @method string              getDependencies()                Returns the current record's "dependencies" value
 * @method string              getSvnCopyFolder()               Returns the current record's "svnCopyFolder" value
 * @method string              getFtpPath()                     Returns the current record's "ftpPath" value
 * @method string              getReleaseUrl()                  Returns the current record's "releaseUrl" value
 * @method string              getTestUrl()                     Returns the current record's "testUrl" value
 * @method enum                getSourceFolderCompressionType() Returns the current record's "sourceFolderCompressionType" value
 * @method Doctrine_Collection getBaseline()                    Returns the current record's "Baseline" collection
 * @method System              setName()                        Sets the current record's "name" value
 * @method System              setAcronym()                     Sets the current record's "acronym" value
 * @method System              setJiraComponent()               Sets the current record's "jiraComponent" value
 * @method System              setDependencies()                Sets the current record's "dependencies" value
 * @method System              setSvnCopyFolder()               Sets the current record's "svnCopyFolder" value
 * @method System              setFtpPath()                     Sets the current record's "ftpPath" value
 * @method System              setReleaseUrl()                  Sets the current record's "releaseUrl" value
 * @method System              setTestUrl()                     Sets the current record's "testUrl" value
 * @method System              setSourceFolderCompressionType() Sets the current record's "sourceFolderCompressionType" value
 * @method System              setBaseline()                    Sets the current record's "Baseline" collection
 * 
 * @package    baselinegenerator
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSystem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('system');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('acronym', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('jiraComponent', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 30,
             ));
        $this->hasColumn('dependencies', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('svnCopyFolder', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('ftpPath', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '/',
             'length' => 255,
             ));
        $this->hasColumn('releaseUrl', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('testUrl', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('sourceFolderCompressionType', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'zip',
              1 => 'tar.gz',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Baseline', array(
             'local' => 'id',
             'foreign' => 'fk_system'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}