<?php

/**
 * BaseBaseline
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $fk_system
 * @property string $name
 * @property enum $type
 * @property boolean $publishToFTP
 * @property boolean $sendMail
 * @property boolean $sendAvailabilityMail
 * @property string $issues
 * @property date $generatedAt
 * @property System $System
 * 
 * @method integer  getFkSystem()             Returns the current record's "fk_system" value
 * @method string   getName()                 Returns the current record's "name" value
 * @method enum     getType()                 Returns the current record's "type" value
 * @method boolean  getPublishToFTP()         Returns the current record's "publishToFTP" value
 * @method boolean  getSendMail()             Returns the current record's "sendMail" value
 * @method boolean  getSendAvailabilityMail() Returns the current record's "sendAvailabilityMail" value
 * @method string   getIssues()               Returns the current record's "issues" value
 * @method date     getGeneratedAt()          Returns the current record's "generatedAt" value
 * @method System   getSystem()               Returns the current record's "System" value
 * @method Baseline setFkSystem()             Sets the current record's "fk_system" value
 * @method Baseline setName()                 Sets the current record's "name" value
 * @method Baseline setType()                 Sets the current record's "type" value
 * @method Baseline setPublishToFTP()         Sets the current record's "publishToFTP" value
 * @method Baseline setSendMail()             Sets the current record's "sendMail" value
 * @method Baseline setSendAvailabilityMail() Sets the current record's "sendAvailabilityMail" value
 * @method Baseline setIssues()               Sets the current record's "issues" value
 * @method Baseline setGeneratedAt()          Sets the current record's "generatedAt" value
 * @method Baseline setSystem()               Sets the current record's "System" value
 * 
 * @package    baselinegenerator
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBaseline extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('baseline');
        $this->hasColumn('fk_system', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Teste',
              1 => 'Release',
             ),
             ));
        $this->hasColumn('publishToFTP', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('sendMail', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('sendAvailabilityMail', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('issues', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
        $this->hasColumn('generatedAt', 'date', null, array(
             'type' => 'date',
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('System', array(
             'local' => 'fk_system',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzBlameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}