<?php

/**
 * Baseline
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    baselinegenerator
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 *
 * @todo Change the constants value to English to normalize the system, apply i18n on the possible database values
 */
class Baseline extends BaseBaseline
{

	/**
	 * @var string
	 */
	const TYPE_RELEASE = 'Release';

	/**
	 * @var string
	 */
	const TYPE_TEST = 'Teste';


	/**
	 * @return bool
	 */
	public function isTestBaseline() {
		return (strcasecmp($this->getType(), self::TYPE_TEST) == 0);
	}

	/**
	 * @return bool
	 */
	public function isReleaseBaseline() {
		return (strcasecmp($this->getType(), self::TYPE_RELEASE) == 0);
	}
}