<?php

/**
 * BaselineTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BaselineTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object BaselineTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Baseline');
    }
}