<?php

/**
 * ParameterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ParameterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ParameterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Parameter');
    }
}