<?php

/**
 * SystemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SystemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SystemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('System');
    }
}