<?php

/**
 * BasevjGuardADGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $guid
 * @property string $name
 * @property string $description
 * @property boolean $is_activated
 * @property Doctrine_Collection $users
 * @property Doctrine_Collection $permissions
 * @property Doctrine_Collection $vjGuardADGroupPermission
 * @property Doctrine_Collection $vjGuardADUserGroup
 * 
 * @method string              getGuid()                     Returns the current record's "guid" value
 * @method string              getName()                     Returns the current record's "name" value
 * @method string              getDescription()              Returns the current record's "description" value
 * @method boolean             getIsActivated()              Returns the current record's "is_activated" value
 * @method Doctrine_Collection getUsers()                    Returns the current record's "users" collection
 * @method Doctrine_Collection getPermissions()              Returns the current record's "permissions" collection
 * @method Doctrine_Collection getVjGuardADGroupPermission() Returns the current record's "vjGuardADGroupPermission" collection
 * @method Doctrine_Collection getVjGuardADUserGroup()       Returns the current record's "vjGuardADUserGroup" collection
 * @method vjGuardADGroup      setGuid()                     Sets the current record's "guid" value
 * @method vjGuardADGroup      setName()                     Sets the current record's "name" value
 * @method vjGuardADGroup      setDescription()              Sets the current record's "description" value
 * @method vjGuardADGroup      setIsActivated()              Sets the current record's "is_activated" value
 * @method vjGuardADGroup      setUsers()                    Sets the current record's "users" collection
 * @method vjGuardADGroup      setPermissions()              Sets the current record's "permissions" collection
 * @method vjGuardADGroup      setVjGuardADGroupPermission() Sets the current record's "vjGuardADGroupPermission" collection
 * @method vjGuardADGroup      setVjGuardADUserGroup()       Sets the current record's "vjGuardADUserGroup" collection
 * 
 * @package    baselinegenerator
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasevjGuardADGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vj_guard_a_d_group');
        $this->hasColumn('guid', 'string', 32, array(
             'type' => 'string',
             'unique' => true,
             'length' => 32,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('is_activated', 'boolean', null, array(
             'type' => 'boolean',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('vjGuardADUser as users', array(
             'refClass' => 'vjGuardADUserGroup',
             'local' => 'group_id',
             'foreign' => 'user_id'));

        $this->hasMany('vjGuardADPermission as permissions', array(
             'refClass' => 'vjGuardADGroupPermission',
             'local' => 'group_id',
             'foreign' => 'permission_id'));

        $this->hasMany('vjGuardADGroupPermission', array(
             'local' => 'id',
             'foreign' => 'group_id'));

        $this->hasMany('vjGuardADUserGroup', array(
             'local' => 'id',
             'foreign' => 'group_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}