<?php

/**
 * BasevjGuardADUserGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $group_id
 * @property vjGuardADUser $vjGuardADUser
 * @property vjGuardADGroup $vjGuardADGroup
 * 
 * @method integer            getUserId()         Returns the current record's "user_id" value
 * @method integer            getGroupId()        Returns the current record's "group_id" value
 * @method vjGuardADUser      getVjGuardADUser()  Returns the current record's "vjGuardADUser" value
 * @method vjGuardADGroup     getVjGuardADGroup() Returns the current record's "vjGuardADGroup" value
 * @method vjGuardADUserGroup setUserId()         Sets the current record's "user_id" value
 * @method vjGuardADUserGroup setGroupId()        Sets the current record's "group_id" value
 * @method vjGuardADUserGroup setVjGuardADUser()  Sets the current record's "vjGuardADUser" value
 * @method vjGuardADUserGroup setVjGuardADGroup() Sets the current record's "vjGuardADGroup" value
 * 
 * @package    baselinegenerator
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasevjGuardADUserGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vj_guard_a_d_user_group');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('group_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('vjGuardADUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('vjGuardADGroup', array(
             'local' => 'group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}