<?php

/**
 * BasevjGuardADUserPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $permission_id
 * @property vjGuardADUser $vjGuardADUser
 * @property vjGuardADPermission $vjGuardADPermission
 * 
 * @method integer                 getUserId()              Returns the current record's "user_id" value
 * @method integer                 getPermissionId()        Returns the current record's "permission_id" value
 * @method vjGuardADUser           getVjGuardADUser()       Returns the current record's "vjGuardADUser" value
 * @method vjGuardADPermission     getVjGuardADPermission() Returns the current record's "vjGuardADPermission" value
 * @method vjGuardADUserPermission setUserId()              Sets the current record's "user_id" value
 * @method vjGuardADUserPermission setPermissionId()        Sets the current record's "permission_id" value
 * @method vjGuardADUserPermission setVjGuardADUser()       Sets the current record's "vjGuardADUser" value
 * @method vjGuardADUserPermission setVjGuardADPermission() Sets the current record's "vjGuardADPermission" value
 * 
 * @package    baselinegenerator
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasevjGuardADUserPermission extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vj_guard_a_d_user_permission');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('permission_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('vjGuardADUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('vjGuardADPermission', array(
             'local' => 'permission_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}