<?php

/**
 * vjGuardADUserPermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class vjGuardADUserPermissionTable extends PluginvjGuardADUserPermissionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object vjGuardADUserPermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('vjGuardADUserPermission');
    }
}