<?php

/**
 * vjGuardADUserGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class vjGuardADUserGroupTable extends PluginvjGuardADUserGroupTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object vjGuardADUserGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('vjGuardADUserGroup');
    }
}