<?php

/**
 * vjGuardADUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class vjGuardADUserTable extends PluginvjGuardADUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object vjGuardADUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('vjGuardADUser');
    }
}