<?php

/**
 * vjGuardADGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class vjGuardADGroupTable extends PluginvjGuardADGroupTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object vjGuardADGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('vjGuardADGroup');
    }
}