<?php

/**
 * vjGuardADPermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class vjGuardADPermissionTable extends PluginvjGuardADPermissionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object vjGuardADPermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('vjGuardADPermission');
    }
}