<?php

/**
 * vjGuardADGroupPermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class vjGuardADGroupPermissionTable extends PluginvjGuardADGroupPermissionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object vjGuardADGroupPermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('vjGuardADGroupPermission');
    }
}