<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginvjGuardADPermission extends BasevjGuardADPermission
{
  public function save(Doctrine_Connection $con = null)
  {
    if(is_array($this->name))
    {
      $this->name = $this->name[0];
      $this->description = $this->description[0];
    }
    return parent::save($con);
  }
}