<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginvjGuardADGroup extends BasevjGuardADGroup
{
  public function getScreenName() {
    if(ad::getSecureGroupName()!==false)
    {
      return substr($this->getName(), 0, -(strlen(ad::getSecureGroupName())));
    }
    else
    {
      return $this->getName();
    }
  }

  public function save(Doctrine_Connection $con = null)
  {
    if($this->isNew() && $this->created_at===null){
      $name = $this->name;
      if(ad::getSecureGroupName()!==false) $name.=ad::getSecureGroupName();
      $this->setName($name);
      $guid = ad::createGroupInADAndReturnGuid($name, $this->description);
      if($guid=="") throw new sfException("Problem with group creation");
      $this->setGuid($guid);
      $this->setIsActivated(true);
    }
    if(is_array($this->name))
    {
      $this->guid = $this->guid[0];
      $this->name = $this->name[0];
      $this->description = $this->description[0];
      $this->is_activated = $this->is_activated[0];
    }
    return parent::save($con);
  }
}