<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('baseline', 'created_by', 'integer', '8', array(
             'notnull' => '',
             ));
        $this->addColumn('baseline', 'updated_by', 'integer', '8', array(
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('baseline', 'created_by');
        $this->removeColumn('baseline', 'updated_by');
    }
}